### ISSUE TITLE
Essence Markers on Armor

### ISSUE THREAD

**Issue by Mewimi** [Epithumia/ManaForge#6]
Appears the forge has issues identifying the correct active marker for armor pieces, possibly weapons too.   For example, the below code shows Salamander as being active, when it should be Gnome.  Verified in-game.   Great calculator though! :)

23
47
18 23 23 107

**Comment by Epithumia** [comment]
Weapons are straightforward, armors have their resistance wheel backwards in the forge compared to in-game, it's easily fixed (tomorrow, probably).

**Comment by Mewimi** [comment]
> Weapons are straightforward, armors have their resistance wheel backwards in the forge compared to in-game, it's easily fixed (tomorrow, probably).

Great Epithumia you rock!   Slightly different, but kinda similar.  More of a quality of life kind of thing.  Any chance you could position the immunity markers to match how it shows up in game as well?   For example, poison marker should be under wisp, as displayed in game.  Exact order in game being:

Poison, Darkness, Paralysis, Confusion, Burn, Sleep, Petrification, Freeze.  At least in the NA version, not sure if it is different in other ones.

**Comment by Epithumia** [comment]
> Appears the forge has issues identifying the correct active marker for armor pieces, possibly weapons too. For example, the below code shows Salamander as being active, when it should be Gnome. Verified in-game. Great calculator though! :)
> 
> 23 47 18 23 23 107

In game, at this exact step, the only marker is Jinn, though. Still my code was wrong and showing undine first then sala when it should have been gnome then jinn.


> > Weapons are straightforward, armors have their resistance wheel backwards in the forge compared to in-game, it's easily fixed (tomorrow, probably).
> 
> Great Epithumia you rock! Slightly different, but kinda similar. More of a quality of life kind of thing. Any chance you could position the immunity markers to match how it shows up in game as well? For example, poison marker should be under wisp, as displayed in game. Exact order in game being:
> 
> Poison, Darkness, Paralysis, Confusion, Burn, Sleep, Petrification, Freeze. At least in the NA version, not sure if it is different in other ones.

It's easy to fix that too.
